/** @type {import('tailwindcss').Config} */
import textStroke from "@designbycode/tailwindcss-text-stroke";

export default {
  content: [
    "./index.html",
    "./src/App.jsx",
    "./src/main.jsx",
    "./src/Components/Main Components/Nav.jsx",
    "./src/Components/Main Components/Home.jsx",
    "./src/Components/Home Page/SectionHome.jsx",
    "./src/Components/Home Page/SectionFeatured.jsx",
    "./src/Components/Home Page/FeaturedWatchComponent.jsx",
    "./src/Components/Home Page/SectionOurStory.jsx",
    "./src/Components/Home Page/SectionProducts.jsx",
    "./src/Components/Home Page/Product.jsx",
    "./src/Components/Home Page/SectionReviews.jsx",
    "./src/Components/Home Page/SectionNewArivals.jsx",
    "./src/Components/Home Page/NewArival.jsx",
    "./src/Components/Home Page/SectionSubscribe.jsx",
    "./src/Components/Main Components/Footer.jsx",
    "./src/Components/Main Components/Cart.jsx",
    "./src/Components/Main Components/Products.jsx",
    "./src/Components/Products Page/Product.jsx",
    "./src/Components/Products Page/ProductView.jsx",
    "./src/Components/Cart Page/CartProduct.jsx",
    "./src/Components/Cart Page/Checkout.jsx",
    "./src/Components/Cart Page/Reciept.jsx",
    "./src/Components/Cart Page/ReceiptPage.jsx",
    "./src/Components/Main Components/NotFound.jsx",
    "./src/Components/Main Components/layout/Inner/Inner.jsx",
    "./src/Components/Main Components/layout/Inner/Scroll.jsx",
    "./src/Components/Support-Center Page/HeaderSupport.jsx",
    "./src/Components/Main Components/SupportCenter.jsx",
    "./src/Components/Support-Center Page/Questions.jsx",
    "./src/Components/Main Components/Splash.jsx",
    "./src/Components/Support-Center Page/GetInTouch.jsx",
    "./src/Components/Main Components/layout/Inner/FlipText.jsx",
    "./src/Components/Main Components/layout/Inner/ScrollHorizontal.jsx",
    "./src/Components/Main Components/Aboutus.jsx",
    "./src/Components/About-us Page/Reckless.jsx",
    "./src/Components/Main Components/CopyRights.jsx",
  ],
  theme: {
    rotate: {
      270: "270deg",
    },
    extend: {
      fontFamily: {
        custRoboto: [`"Roboto"`, "sans-serif"],
      },
      colors: {
        "light-theme": {
          "first-color": "#FFB568",
          "button-color": "#2B2B2B",
          "first-color-action-alt": "#363636",
          "title-color": "#2E2E2E",
          "text-color": "#595959",
          "text-color-light": "#4D4D4D",
          // "text-color-light": "#575757",
          "body-color": "#FCFCFC",
          "container-color": "#FFFFFF",
          "border-color": "#F0F0F0",
        },
        "dark-theme": {
          "first-color-dark": "#EFBE8A",
          "first-color-action-dark": "#3D3D3D",
          "title-color-dark": "#F2F2F2",
          "text-color-dark": "#BFBFBF",
          "8C8C8C": "#8C8C8C",
          "body-color-dark": "#1F1F1F",
          "container-color-dark": "#292929",
          "border-color-dark": "#333333",
        },
      },
    },
    screens: {
      phone: "320px",
      endPhone: { max: "767px" },
      tablet: "768px",
      endTablet: { max: "991px" },
      endTablentMinMax: { min: "768px", max: "991px" },
      mediumLap: "991px",
      endMediumLap: { min: "991px", max: "1199px" },
      bigLap: "1199px",
      bigLapbefore4k: { min: "1230px", max: "1304px" },
      custommedia: { min: "1199px", max: "1229px" },
    },
  },
  plugins: [textStroke],
  darkMode: "class",
};
